package com.codingshuttle.razorpay.common.enums;

public enum PaymentEvent {
    AUTHORIZE_ATTEMPT,
    AUTHORIZE_SUCCESS,
    AUTHORIZE_FAILED,
    CAPTURE_REQUEST,
    CAPTURE_ATTEMPT,
    CAPTURE_SUCCESS,
    CAPTURE_FAILED,
    REFUND_INITIATED,
    REFUND_SUCCESS,
    REFUND_FAILED,
    SETTLE,
    CANCEL,
    CAPTURE_TIMEOUT
}
